# Sample config file

# These are main level config settings that applies to all sub commands
#device = '/dev/hidAxpert'
#logfile = '-'
#loglevel = 'debug'

# This is for the query sub command
[query]
#mqtt = true
mqtt_host = 'mqtt.host.com'
# Any %s in the topic will be replaces by the actual query request name sent to
# the inverter
mqtt_topic = 'a/new/topic/%s'

# Should the dev_stat bit string entity, returned by the QPIGS query, be parsed
# or left as an 8 char 1s/0s string? Default is to parse this into a nested
# dict of device status bits.
#parse_dev_stat = true
